### ISSUE TITLE
Is this app being maintained?

### ISSUE THREAD

**Issue by sam-artuso** [marcopaganini/termotp#1]
As per subject.

**Comment by marcopaganini** [comment]
Yes it is. Not a lot of changes, since it does what I need :) Do you have a feature in mind?

**Comment by sam-artuso** [comment]
This is a great app and it's a shame it [hasn't got](https://www.reddit.com/r/commandline/comments/10zdnmj/termotp_an_otp_generator_for_your_terminal_with/) the credit it deserves.

I'm in the process of switching to Aegis and this is exactly what I was looking for – a CLI-based companion to their mobile app. I'm using Syncthing to keep the tokens in sync between my phone and my laptop.

The only extra thing I wish this app did, is caching the password somewhere in memory so that I don't need to type it every time. Does this happen to be in your roadmap?

**Comment by sam-artuso** [comment]
It would also be good to be able to pipe the OTPs into [fzf](https://github.com/junegunn/fzf) and use their fuzzy finder instead.

**Comment by marcopaganini** [comment]
So, I just released v0.0.5 which includes fzf support. Just run `termotp` with the `--fzf` command-line option.

I'm considering how to cache passwords. I'd prefer not to do it manually, since anything having to do with credentials needs proper encryption, access control, etc. Maybe using the gnome-keyring for this? It has support to save/retrieve passwords, can open the keyring automatically on login, and can also cache passwords.

Please let me know what you think about the fzf support.

**Comment by sam-artuso** [comment]
Wow, thanks for implementing support for fzf so quickly!

Regarding keyring support, how about using some abstraction layer like [this](https://github.com/zalando/go-keyring) or [this](https://github.com/99designs/keyring)? I think it'd be nice for termotp to work seamlessly on any platform. Personally I switch a lot between Linux and MacOS.

**Comment by marcopaganini** [comment]
LOL, those were exactly the two libraries I was looking at :)

Yes, the idea is to use one of those so we get cross-platform support.
